### ISSUE TITLE
Error installing requirements due to conflict

### ISSUE THREAD

**Issue by micahjsmith** [HDI-Project/AutoBazaar#25]
* AutoBazaar version: c3fe6d2c8cea4bed3a61cf6197fc93cef36f6a3d
* Python version: 3.7
* Operating System (`python -c 'import platform;print(platform.platform())'`): ubuntu

### Description

Test failure from https://github.com/HDI-Project/AutoBazaar/runs/1254222093?check_suite_focus=true

Reproduced locally on latest master (c3fe6d2c8cea4bed3a61cf6197fc93cef36f6a3d)

### What I Did

```
$ make test
python -m rundoc run --single-session bash -t bash README.md

Running code blocks from supplied documentation.
Modify and/or confirm displayed code by pressing Return.

=== Step 1/1 [bash]
abz search 185_baseball -c10,20,30 -b10
abz search 185_baseball -c10,20,30 -b10 -r results.csv

Traceback (most recent call last):
  File "/Users/micahsmith/.pyenv/versions/3.7.7/envs/autobazaar/lib/python3.7/site-packages/pkg_resources/__init__.py", line 567, in _build_master
    ws.require(__requires__)
  File "/Users/micahsmith/.pyenv/versions/3.7.7/envs/autobazaar/lib/python3.7/site-packages/pkg_resources/__init__.py", line 884, in require
    needed = self.resolve(parse_requirements(requirements))
  File "/Users/micahsmith/.pyenv/versions/3.7.7/envs/autobazaar/lib/python3.7/site-packages/pkg_resources/__init__.py", line 775, in resolve
    raise VersionConflict(dist, req).with_context(dependent_req)
pkg_resources.ContextualVersionConflict: (botocore 1.18.16 (/Users/micahsmith/.pyenv/versions/3.7.7/envs/autobazaar/lib/python3.7/site-packages), Requirement.parse('botocore<1.17.45,>=1.17.44'), {'aiobotocore'})

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/micahsmith/.pyenv/versions/autobazaar/bin/abz", line 33, in <module>
    sys.exit(load_entry_point('autobazaar', 'console_scripts', 'abz')())
  File "/Users/micahsmith/.pyenv/versions/autobazaar/bin/abz", line 25, in importlib_load_entry_point
    return next(matches).load()
  File "/Users/micahsmith/.pyenv/versions/3.7.7/envs/autobazaar/lib/python3.7/site-packages/importlib_metadata/__init__.py", line 105, in load
    module = import_module(match.group('module'))
  File "/Users/micahsmith/.pyenv/versions/3.7.7/lib/python3.7/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1006, in _gcd_import
  File "<frozen importlib._bootstrap>", line 983, in _find_and_load
  File "<frozen importlib._bootstrap>", line 967, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 677, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/Users/micahsmith/workspace/AutoBazaar/autobazaar/__main__.py", line 26, in <module>
    from autobazaar.search import TUNERS, PipelineSearcher
  File "/Users/micahsmith/workspace/AutoBazaar/autobazaar/search.py", line 25, in <module>
    from mlblocks.mlpipeline import MLPipeline
  File "/Users/micahsmith/.pyenv/versions/3.7.7/envs/autobazaar/lib/python3.7/site-packages/mlblocks/__init__.py", line 13, in <module>
    from mlblocks.discovery import (
  File "/Users/micahsmith/.pyenv/versions/3.7.7/envs/autobazaar/lib/python3.7/site-packages/mlblocks/discovery.py", line 17, in <module>
    import pkg_resources
  File "/Users/micahsmith/.pyenv/versions/3.7.7/envs/autobazaar/lib/python3.7/site-packages/pkg_resources/__init__.py", line 3238, in <module>
    @_call_aside
  File "/Users/micahsmith/.pyenv/versions/3.7.7/envs/autobazaar/lib/python3.7/site-packages/pkg_resources/__init__.py", line 3222, in _call_aside
    f(*args, **kwargs)
  File "/Users/micahsmith/.pyenv/versions/3.7.7/envs/autobazaar/lib/python3.7/site-packages/pkg_resources/__init__.py", line 3251, in _initialize_master_working_set
    working_set = WorkingSet._build_master()
  File "/Users/micahsmith/.pyenv/versions/3.7.7/envs/autobazaar/lib/python3.7/site-packages/pkg_resources/__init__.py", line 569, in _build_master
    return cls._build_from_requirements(__requires__)
  File "/Users/micahsmith/.pyenv/versions/3.7.7/envs/autobazaar/lib/python3.7/site-packages/pkg_resources/__init__.py", line 582, in _build_from_requirements
    dists = ws.resolve(reqs, Environment())
  File "/Users/micahsmith/.pyenv/versions/3.7.7/envs/autobazaar/lib/python3.7/site-packages/pkg_resources/__init__.py", line 775, in resolve
    raise VersionConflict(dist, req).with_context(dependent_req)
pkg_resources.ContextualVersionConflict: (botocore 1.18.16 (/Users/micahsmith/.pyenv/versions/3.7.7/envs/autobazaar/lib/python3.7/site-packages), Requirement.parse('botocore<1.17.45,>=1.17.44'), {'aiobotocore'})
Traceback (most recent call last):
  File "/Users/micahsmith/.pyenv/versions/3.7.7/envs/autobazaar/lib/python3.7/site-packages/pkg_resources/__init__.py", line 567, in _build_master
    ws.require(__requires__)
  File "/Users/micahsmith/.pyenv/versions/3.7.7/envs/autobazaar/lib/python3.7/site-packages/pkg_resources/__init__.py", line 884, in require
    needed = self.resolve(parse_requirements(requirements))
  File "/Users/micahsmith/.pyenv/versions/3.7.7/envs/autobazaar/lib/python3.7/site-packages/pkg_resources/__init__.py", line 775, in resolve
    raise VersionConflict(dist, req).with_context(dependent_req)
pkg_resources.ContextualVersionConflict: (botocore 1.18.16 (/Users/micahsmith/.pyenv/versions/3.7.7/envs/autobazaar/lib/python3.7/site-packages), Requirement.parse('botocore<1.17.45,>=1.17.44'), {'aiobotocore'})

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/micahsmith/.pyenv/versions/autobazaar/bin/abz", line 33, in <module>
    sys.exit(load_entry_point('autobazaar', 'console_scripts', 'abz')())
  File "/Users/micahsmith/.pyenv/versions/autobazaar/bin/abz", line 25, in importlib_load_entry_point
    return next(matches).load()
  File "/Users/micahsmith/.pyenv/versions/3.7.7/envs/autobazaar/lib/python3.7/site-packages/importlib_metadata/__init__.py", line 105, in load
    module = import_module(match.group('module'))
  File "/Users/micahsmith/.pyenv/versions/3.7.7/lib/python3.7/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1006, in _gcd_import
  File "<frozen importlib._bootstrap>", line 983, in _find_and_load
  File "<frozen importlib._bootstrap>", line 967, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 677, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/Users/micahsmith/workspace/AutoBazaar/autobazaar/__main__.py", line 26, in <module>
    from autobazaar.search import TUNERS, PipelineSearcher
  File "/Users/micahsmith/workspace/AutoBazaar/autobazaar/search.py", line 25, in <module>
    from mlblocks.mlpipeline import MLPipeline
  File "/Users/micahsmith/.pyenv/versions/3.7.7/envs/autobazaar/lib/python3.7/site-packages/mlblocks/__init__.py", line 13, in <module>
    from mlblocks.discovery import (
  File "/Users/micahsmith/.pyenv/versions/3.7.7/envs/autobazaar/lib/python3.7/site-packages/mlblocks/discovery.py", line 17, in <module>
    import pkg_resources
  File "/Users/micahsmith/.pyenv/versions/3.7.7/envs/autobazaar/lib/python3.7/site-packages/pkg_resources/__init__.py", line 3238, in <module>
    @_call_aside
  File "/Users/micahsmith/.pyenv/versions/3.7.7/envs/autobazaar/lib/python3.7/site-packages/pkg_resources/__init__.py", line 3222, in _call_aside
    f(*args, **kwargs)
  File "/Users/micahsmith/.pyenv/versions/3.7.7/envs/autobazaar/lib/python3.7/site-packages/pkg_resources/__init__.py", line 3251, in _initialize_master_working_set
    working_set = WorkingSet._build_master()
  File "/Users/micahsmith/.pyenv/versions/3.7.7/envs/autobazaar/lib/python3.7/site-packages/pkg_resources/__init__.py", line 569, in _build_master
    return cls._build_from_requirements(__requires__)
  File "/Users/micahsmith/.pyenv/versions/3.7.7/envs/autobazaar/lib/python3.7/site-packages/pkg_resources/__init__.py", line 582, in _build_from_requirements
    dists = ws.resolve(reqs, Environment())
  File "/Users/micahsmith/.pyenv/versions/3.7.7/envs/autobazaar/lib/python3.7/site-packages/pkg_resources/__init__.py", line 775, in resolve
    raise VersionConflict(dist, req).with_context(dependent_req)
pkg_resources.ContextualVersionConflict: (botocore 1.18.16 (/Users/micahsmith/.pyenv/versions/3.7.7/envs/autobazaar/lib/python3.7/site-packages), Requirement.parse('botocore<1.17.45,>=1.17.44'), {'aiobotocore'})
==== Failed at step 1 with exit code '1'

make: *** [test-readme] Error 1
```

**Comment by micahjsmith** [comment]
Resolved by 4162e1f
